# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('desc', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('is_recommend', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=15)),
                ('is_delete', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=1)),
                ('r_p', models.ManyToManyField(to='backweb.Permission')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Typess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'typess',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=20, null=True)),
                ('out_time', models.DateTimeField(null=True)),
                ('is_superuser', models.BooleanField(default=0)),
                ('r_u', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='ty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Typess'),
        ),
    ]
